Baseline implementation for obj files
vga-group/tauray pull request #34
Opened 2023-04-18 21:37 UTC by eero-lehtinen

Works for singular meshes.
Doesn't take into account materials or textures.

I can't get windows to build, but add assimp to vcpkg just in case.

2023-04-20 07:05 UTC, juliusikkala reviewed
It seems to be on the right track, especially once the materials start working. Because the implementation is done using ASSIMP, I don't think there's a reason for the loader to be specific to .obj, right? Maybe this could be a generic fallback loader whenever the format is not .ply or .glb.

2023-04-20 07:05 UTC, juliusikkala commented on test/monkey.obj
I would prefer that these testing .obj files wouldn't be in the repo. `test.glb` should be enough, I didn't intend it to be a file format test but rendering tests instead. The reason I'm pretty strict about this is that I have seen too many 500mb repos where it's all just oversized test data. The `test.obj` here is 211k lines of diff as well :D

2023-04-20 07:05 UTC, juliusikkala commented on src/obj.cc
> +    md.cameras["default"] = camera();
No need, there should be a default camera already without this.

2023-05-02 15:40 UTC, eero-lehtinen commented on test/monkey.obj
I force pushed a new commit without these so they won't bloat git history.

2023-05-10 11:33 UTC, juliusikkala requested changes
Seems to be mostly fine, for an experimental importer for now. I'll probably add animations + do something about deducing the metallic and roughness factors from phong parameters at some point later on.

Once the tangent thing is fixed, I think this is ready for merging from my point of view.

2023-05-10 11:33 UTC, juliusikkala commented on src/assimp.cc
> +                1.0f
It's indeed not, and the correct value can be calculated from the mBitangents member. See https://github.com/vga-group/tauray/blob/ad3773041877e16be9d8157b1ad973d50e1fc98d/shader/forward.vert#L32 for how it's used. 
I think the correct value here would be `sign(dot(ai_mesh->mBitangents[j], cross(ai_mesh->mNormals[j], ai_mesh->mTangents[j])))`.

2023-05-11 12:09 UTC, merged